### ISSUE TITLE
Usage with maven 3.5.4

### ISSUE THREAD

**Issue by albinscode** [joow/jpa-hibernate-archetype#1]
Just for your information with maven 3.5.4 I was not able to run properly the generation command without specifying the archetype version. As maven was not able to find the archetype it was proposing the full available list of archetypes (several thousands), so I used:

~~~
mvn archetype:generate -DarchetypeGroupId=org.joow -DarchetypeArtifactId=jpa-hibernate-archetype -DarchetypeVersion=1.0-SNAPSHOT
~~~

**Comment by joow** [comment]
Many thanks for your report.

I tried on the latest Maven version (3.6.0) and got the same issue.
I updated the documentation accordingly.

**Comment by albinscode** [comment]
Thanks for your repo and your fix, it is useful!
